export enum PrismaClientKnownRequestErrorCode {
  // 1000番台: 接続・認証系
  AuthenticationFailed = 'P1000',
  DatabaseUnreachable = 'P1001',
  DatabaseTimeout = 'P1002',
  DatabaseDoesNotExist = 'P1003',
  OperationTimeout = 'P1008',
  DatabaseAlreadyExists = 'P1009',
  UserAccessDenied = 'P1010',
  TlsConnectionError = 'P1011',
  SchemaValidationError = 'P1012',
  InvalidDatabaseString = 'P1013',
  UnderlyingModelError = 'P1014',
  UnsupportedDatabaseVersion = 'P1015',
  IncorrectParameters = 'P1016',
  ServerClosedConnection = 'P1017',

  // 2000番台: クエリエンジン・ユーザーデータ系
  ValueTooLong = 'P2000',
  RecordDoesNotExist = 'P2001',
  UniqueConstraintFailed = 'P2002',
  ForeignKeyConstraintFailed = 'P2003',
  DatabaseConstraintFailed = 'P2004',
  InvalidFieldValue = 'P2005',
  InvalidValue = 'P2006',
  DataValidationError = 'P2007',
  QueryParsingError = 'P2008',
  QueryValidationError = 'P2009',
  RawQueryFailed = 'P2010',
  NullConstraintViolation = 'P2011',
  MissingRequiredValue = 'P2012',
  MissingRequiredArgument = 'P2013',
  RelationViolation = 'P2014',
  RelatedRecordNotFound = 'P2015',
  QueryInterpretationError = 'P2016',
  RecordsNotConnected = 'P2017',
  ConnectedRecordsNotFound = 'P2018',
  InputError = 'P2019',
  ValueOutOfRange = 'P2020',
  TableDoesNotExist = 'P2021',
  ColumnDoesNotExist = 'P2022',
  InconsistentColumnData = 'P2023',
  ConnectionPoolTimeout = 'P2024',
  OperationFailed = 'P2025',
  UnsupportedFeature = 'P2026',
  DatabaseQueryExecutionErrors = 'P2027',
  TransactionApiError = 'P2028',
  FulltextIndexNotFound = 'P2030',
  MongoDBReplicaSetError = 'P2031',
  NumberOutOfRange = 'P2033',
  TransactionConflict = 'P2034',

  // 3000番台: マイグレーション・スキーマエンジン
  DatabaseCreationFailed = 'P3000',
  MigrationDestructiveChanges = 'P3001',
  MigrationRollbackError = 'P3002',
  MigrationFormatChanged = 'P3003',
  SystemDatabaseAlterationError = 'P3004',
  NonEmptySchemaError = 'P3005',
  FailedMigrationError = 'P3006',
  PreviewFeaturesBlockedError = 'P3007',
  MigrationAlreadyAppliedError = 'P3008',
  FailedMigrationsError = 'P3009',
  MigrationNameTooLongError = 'P3010',
  MigrationNotFoundForRollbackError = 'P3011',
  MigrationNotInFailedStateError = 'P3012',
  ProviderArraysNotSupportedError = 'P3013',
  ShadowDatabaseCreationError = 'P3014',
  MigrationFileNotFoundError = 'P3015',
  DatabaseResetFallbackFailedError = 'P3016',
  MigrationNotFoundError = 'P3017',
  MigrationFailedToApplyError = 'P3018',
  ProviderMismatchError = 'P3019',
  ShadowDatabaseDisabledError = 'P3020',
  NoForeignKeysError = 'P3021',
  NoDirectDdlError = 'P3022',

  // 4000番台: introspection
  IntrospectionFailed = 'P4000',
  EmptyIntrospectedDatabase = 'P4001',
  InconsistentIntrospectedSchema = 'P4002',

  // 5000番台: Data Proxy
  DataProxyRequestError = 'P5000',
  DataProxyRetryRequestError = 'P5001',
  DataProxyInvalidDatasourceError = 'P5002',
  DataProxyResourceNotFoundError = 'P5003',
  DataProxyFeatureNotImplementedError = 'P5004',
  DataProxySchemaUploadError = 'P5005',
  DataProxyUnknownServerError = 'P5006',
  DataProxyUnauthorizedError = 'P5007',
  DataProxyUsageExceededError = 'P5008',
  DataProxyRequestTimeoutError = 'P5009',
  DataProxyFetchError = 'P5010',
  DataProxyInvalidRequestParametersError = 'P5011',
  DataProxyUnsupportedEngineVersionError = 'P5012',
  DataProxyEngineStartupError = 'P5013',
  DataProxyUnknownEngineStartupError = 'P5014',
  DataProxyInteractiveTransactionError = 'P5015',
}

export const userErrors = [
  PrismaClientKnownRequestErrorCode.ValueTooLong,
  PrismaClientKnownRequestErrorCode.RecordDoesNotExist,
  PrismaClientKnownRequestErrorCode.UniqueConstraintFailed,
  PrismaClientKnownRequestErrorCode.ForeignKeyConstraintFailed,
  PrismaClientKnownRequestErrorCode.DatabaseConstraintFailed,
  PrismaClientKnownRequestErrorCode.InvalidFieldValue,
  PrismaClientKnownRequestErrorCode.InvalidValue,
  PrismaClientKnownRequestErrorCode.DataValidationError,
  PrismaClientKnownRequestErrorCode.QueryParsingError,
  PrismaClientKnownRequestErrorCode.QueryValidationError,
  PrismaClientKnownRequestErrorCode.RawQueryFailed,
  PrismaClientKnownRequestErrorCode.NullConstraintViolation,
  PrismaClientKnownRequestErrorCode.MissingRequiredValue,
  PrismaClientKnownRequestErrorCode.MissingRequiredArgument,
  PrismaClientKnownRequestErrorCode.RelationViolation,
  PrismaClientKnownRequestErrorCode.RelatedRecordNotFound,
  PrismaClientKnownRequestErrorCode.QueryInterpretationError,
  PrismaClientKnownRequestErrorCode.RecordsNotConnected,
  PrismaClientKnownRequestErrorCode.ConnectedRecordsNotFound,
  PrismaClientKnownRequestErrorCode.InputError,
  PrismaClientKnownRequestErrorCode.ValueOutOfRange,
  PrismaClientKnownRequestErrorCode.TableDoesNotExist,
  PrismaClientKnownRequestErrorCode.ColumnDoesNotExist,
  PrismaClientKnownRequestErrorCode.InconsistentColumnData,
  PrismaClientKnownRequestErrorCode.ConnectionPoolTimeout,
  PrismaClientKnownRequestErrorCode.OperationFailed,
  PrismaClientKnownRequestErrorCode.UnsupportedFeature,
  PrismaClientKnownRequestErrorCode.DatabaseQueryExecutionErrors,
  PrismaClientKnownRequestErrorCode.TransactionApiError,
  PrismaClientKnownRequestErrorCode.FulltextIndexNotFound,
  PrismaClientKnownRequestErrorCode.MongoDBReplicaSetError,
  PrismaClientKnownRequestErrorCode.NumberOutOfRange,
  PrismaClientKnownRequestErrorCode.TransactionConflict,
] as const;

export type UserErrorType = (typeof userErrors)[number];
